services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pulsescore
      POSTGRES_PASSWORD: pulsescore
      POSTGRES_DB: pulsescore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulsescore"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./apps/api
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://pulsescore:pulsescore@postgres:5432/pulsescore
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    environment:
      API_URL: http://api:3001
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_TZ: Europe/Paris
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api

volumes:
  postgres_data:
