FROM node:24-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN DATABASE_URL=postgresql://placeholder:placeholder@localhost/placeholder npx prisma generate

EXPOSE 3001

CMD ["sleep", "infinity"]
