app = "pulsescore-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"
  build-target = "prod"

[env]
  NODE_ENV = "production"
  PORT = "3001"
  APIFOOTBALL_TIMEZONE = "Europe/Paris"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    method = "GET"
    path = "/health"
    interval = "15s"
    timeout = "5s"
    grace_period = "20s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
